### ISSUE TITLE
Priority List

### ISSUE THREAD

**Issue by melms** [mehlms/Casting-Portal#28]
- Casting Call (additional actors, additional audition times)
- Listview of open casting calls
- Notification System
- Prioritizing Actor list to Directors
- Prioritizing Casting Call list to Actors
- Settings Page
- Homepage Feed + Activity, pulled from subscriptions
- Subscription Mechanism
- Profile Completion (Including reels, videos, recommendation)
- Search Mechanism + Filters
- Profile Activity
- Pulling "realtime" notifications
- Update UI designs to EVERY page

**Comment by benda106** [comment]
1) Casting Call (additional actors, additional audition times)
2) Listview of open casting calls
3) Port to Laravel
4) Notification System
5) Prioritizing Actor list to Directors
6) Prioritizing Casting Call list to Actors
7) Search Mechanism + Filters
8) Homepage Feed + Activity, pulled from subscriptions
9)Subscription Mechanism
10) Profile Completion (Including reels, videos, recommendation)
11)Profile Activity
12) Pulling "real-time" notifications
13) Settings Page
14) Update UI designs to EVERY page

**Comment by melms** [comment]
1) Casting Call Form (additional actors, additional audition times)
1.5) Casting Call Detail
2) Listview of open casting calls
3) Port to Laravel
4) Notification System
5) Prioritizing Actor list to Directors
6) Prioritizing Casting Call list to Actors
7) Search Mechanism + Filters
8) Homepage Feed + Activity, pulled from subscriptions
9)Subscription Mechanism
10) Profile Completion (Including reels, videos, recommendation)
11)Profile Activity
12) Pulling "real-time" notifications
13) Settings Page
14) Update UI designs to EVERY page
